### ISSUE TITLE
Number Of Board States

### ISSUE THREAD

**Issue by SwiftGodDev** [wrbernardoni/Baseline-Bots#1]
How to increase number of stored possible board states for stocky_inference?

**Comment by wrbernardoni** [comment]
Sorry it's some magic number stuff going on so it's a bit scattered. In my later version I have that in a variable but that version has some stuff that I'm not fully ready to publish.

The lines for the cutoff are: 160, 190, 230 -- Change that 500 value to whatever you want (preferably a variable)
Then for how many boards to keep when you do do a cutoff change the constants in: 162, 192, 243

I do want to note though that the bot's performance doesn't really go up with more board states, if anything it actually gets to be a bit overcautious. To fix this you need to give it a probability distribution over the potential boards and go based off of expectation and not minimax.

**Comment by SwiftGodDev** [comment]
So when can we expect a neural network version of stocky_inference?
